// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace qelec.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("qelec.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("InvoiceDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JobDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("qelec.Models.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TimeSlotId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TimeSlotId");

                    b.ToTable("TimeSlot");

                    b.HasData(
                        new
                        {
                            TimeSlotId = 1,
                            Date = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 2,
                            Date = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 3,
                            Date = new DateTime(2024, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 4,
                            Date = new DateTime(2024, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 5,
                            Date = new DateTime(2024, 10, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 6,
                            Date = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 7,
                            Date = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 8,
                            Date = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 9,
                            Date = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 10,
                            Date = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 11,
                            Date = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 12,
                            Date = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 13,
                            Date = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 14,
                            Date = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 15,
                            Date = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 16,
                            Date = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 17,
                            Date = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 18,
                            Date = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 19,
                            Date = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 20,
                            Date = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 21,
                            Date = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 22,
                            Date = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 23,
                            Date = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 24,
                            Date = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 25,
                            Date = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 26,
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 27,
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 28,
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 29,
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 30,
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 31,
                            Date = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 32,
                            Date = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 33,
                            Date = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 34,
                            Date = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 35,
                            Date = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 36,
                            Date = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 37,
                            Date = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 38,
                            Date = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 39,
                            Date = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 40,
                            Date = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 41,
                            Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 42,
                            Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 43,
                            Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 44,
                            Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 45,
                            Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 46,
                            Date = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 47,
                            Date = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 48,
                            Date = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 49,
                            Date = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 50,
                            Date = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 51,
                            Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 52,
                            Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 53,
                            Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 54,
                            Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 55,
                            Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 56,
                            Date = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 57,
                            Date = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 58,
                            Date = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 59,
                            Date = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 60,
                            Date = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 61,
                            Date = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 62,
                            Date = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 63,
                            Date = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 64,
                            Date = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 65,
                            Date = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 66,
                            Date = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 67,
                            Date = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 68,
                            Date = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 69,
                            Date = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 70,
                            Date = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 71,
                            Date = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 72,
                            Date = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 73,
                            Date = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 74,
                            Date = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 75,
                            Date = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 76,
                            Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 77,
                            Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 78,
                            Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 79,
                            Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 80,
                            Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 81,
                            Date = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 82,
                            Date = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 83,
                            Date = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 84,
                            Date = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 85,
                            Date = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 86,
                            Date = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 87,
                            Date = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 88,
                            Date = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 89,
                            Date = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 90,
                            Date = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 91,
                            Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 92,
                            Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 93,
                            Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 94,
                            Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 95,
                            Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 96,
                            Date = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 97,
                            Date = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 98,
                            Date = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 99,
                            Date = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 100,
                            Date = new DateTime(2024, 11, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 101,
                            Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 102,
                            Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 103,
                            Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 104,
                            Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 105,
                            Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 106,
                            Date = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 107,
                            Date = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 108,
                            Date = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 109,
                            Date = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 110,
                            Date = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 111,
                            Date = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 112,
                            Date = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 113,
                            Date = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 114,
                            Date = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 115,
                            Date = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 116,
                            Date = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 117,
                            Date = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 118,
                            Date = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 119,
                            Date = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 120,
                            Date = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 121,
                            Date = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 122,
                            Date = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 123,
                            Date = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 124,
                            Date = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 125,
                            Date = new DateTime(2024, 11, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 126,
                            Date = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 127,
                            Date = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 128,
                            Date = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 129,
                            Date = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 130,
                            Date = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 131,
                            Date = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 132,
                            Date = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 133,
                            Date = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 134,
                            Date = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 135,
                            Date = new DateTime(2024, 11, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 136,
                            Date = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 137,
                            Date = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 138,
                            Date = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 139,
                            Date = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 140,
                            Date = new DateTime(2024, 11, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 141,
                            Date = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 142,
                            Date = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 143,
                            Date = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 144,
                            Date = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 145,
                            Date = new DateTime(2024, 11, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 146,
                            Date = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 147,
                            Date = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 148,
                            Date = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 149,
                            Date = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 150,
                            Date = new DateTime(2024, 11, 29, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "14:00"
                        },
                        new
                        {
                            TimeSlotId = 151,
                            Date = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "10:00"
                        },
                        new
                        {
                            TimeSlotId = 152,
                            Date = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "11:00"
                        },
                        new
                        {
                            TimeSlotId = 153,
                            Date = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "12:00"
                        },
                        new
                        {
                            TimeSlotId = 154,
                            Date = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = false,
                            Time = "13:00"
                        },
                        new
                        {
                            TimeSlotId = 155,
                            Date = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsAvailable = true,
                            Time = "14:00"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
